// Perbandingan Lebih Besar
let lebihBesar1 = 5 > 3;
console.log(lebihBesar1);
let lebihBesar2 = 10 > 100;
console.log(lebihBesar2);
let lebihBesar3 = "ayam" > "t-rex";
console.log(lebihBesar3);
let lebihBesar4 = 5 > 2;
console.log(lebihBesar4);
let lebihBesar5 = true > false;
console.log(lebihBesar5);
let lebihBesar6 = null > 0;
console.log(lebihBesar6);
let lebihBesar7 = undefined > 0;
console.log(lebihBesar7);
let lebihBesar8 = NaN > 0;
console.log(lebihBesar8);
let lebihBesar9 = 100 > 100;
console.log(lebihBesar9); 
let lebihBesar10 = -1 > 0;
console.log(lebihBesar10);

// Perbandingan Lebih Kecil
let lebihKecil1 = 5 < 3;
console.log(lebihKecil1);
let lebihKecil2 = 10 < 100;
console.log(lebihKecil2);
let lebihKecil3 = "ayam" < "t-rex";
console.log(lebihKecil3);
let lebihKecil4 = 5 < 2;
console.log(lebihKecil4);
let lebihKecil5 = true < false;
console.log(lebihKecil5);
let lebihKecil6 = null < 0;
console.log(lebihKecil6);
let lebihKecil7 = undefined < 0;
console.log(lebihKecil7);
let lebihKecil8 = NaN < 0;
console.log(lebihKecil8);
let lebihKecil9 = 100 < 100;
console.log(lebihKecil9); 
let lebihKecil10 = -1 < 0;
console.log(lebihKecil10);

// Perbandingan Lebih Besar Sama Dengan
let lebihBesarSamaDengan1 = 5 >= 3;
console.log(lebihBesarSamaDengan1);
let lebihBesarSamaDengan2 = 10 >= 100;
console.log(lebihBesarSamaDengan2);
let lebihBesarSamaDengan3 = "ayam" >= "t-rex";
console.log(lebihBesarSamaDengan3);
let lebihBesarSamaDengan4 = 5 >= 2;
console.log(lebihBesarSamaDengan4);
let lebihBesarSamaDengan5 = true >= false;
console.log(lebihBesarSamaDengan5);
let lebihBesarSamaDengan6 = null >= 0;
console.log(lebihBesarSamaDengan6);
let lebihBesarSamaDengan7 = undefined >= 0;
console.log(lebihBesarSamaDengan7);
let lebihBesarSamaDengan8 = NaN >= 0;
console.log(lebihBesarSamaDengan8);
let lebihBesarSamaDengan9 = 100 >= 100;
console.log(lebihBesarSamaDengan9); 
let lebihBesarSamaDengan10 = -1 >= 0;
console.log(lebihBesarSamaDengan10);

// Perbandingan Lebih Kecil Sama Dengan
let lebihKecilSamaDengan1 = 5 <= 3;
console.log(lebihKecilSamaDengan1);
let lebihKecilSamaDengan2 = 10 <= 100;
console.log(lebihKecilSamaDengan2);
let lebihKecilSamaDengan3 = "ayam" <= "t-rex";
console.log(lebihKecilSamaDengan3);
let lebihKecilSamaDengan4 = 5 <= 2;
console.log(lebihKecilSamaDengan4);
let lebihKecilSamaDengan5 = true <= false;
console.log(lebihKecilSamaDengan5);
let lebihKecilSamaDengan6 = null <= 0;
console.log(lebihKecilSamaDengan6);
let lebihKecilSamaDengan7 = undefined <= 0;
console.log(lebihKecilSamaDengan7);
let lebihKecilSamaDengan8 = NaN <= 0;
console.log(lebihKecilSamaDengan8);
let lebihKecilSamaDengan9 = 100 <= 100;
console.log(lebihKecilSamaDengan9); 
let lebihKecilSamaDengan10 = -1 <= 0;
console.log(lebihKecilSamaDengan10);

// Perbandingan Sama Dengan
let equal1 = 5 == 3;
console.log(equal1);
let equal2 = 10 == 100;
console.log(equal2);
let equal3 = "ayam" == "t-rex";
console.log(equal3);
let equal4 = 5 == 2;
console.log(equal4);
let equal5 = true == false;
console.log(equal5);
let equal6 = null == 0;
console.log(equal6);
let equal7 = undefined == 0;
console.log(equal7);
let equal8 = NaN == 0;
console.log(equal8);
let equal9 = 100 == 100;
console.log(equal9); 
let equal10 = -1 == 0;
console.log(equal10);

// Perbandingan Sama Dengan termasuk Tipe Datanya
let equalTo1 = 5 === 3;
console.log(equalTo1);
let equalTo2 = 10 === 100;
console.log(equalTo2);
let equalTo3 = "ayam" === "t-rex";
console.log(equalTo3);
let equalTo4 = 5 === 2;
console.log(equalTo4);
let equalTo5 = true === false;
console.log(equalTo5);
let equalTo6 = null === 0;
console.log(equalTo6);
let equalTo7 = undefined === 0;
console.log(equalTo7);
let equalTo8 = NaN === 0;
console.log(equalTo8);
let equalTo9 = 100 === 100;
console.log(equalTo9); 
let equalTo10 = -1 === 0;
console.log(equalTo10);

// Perbandingan Tidak Sama Dengan
let notEqual1 = 5 != 3;
console.log(notEqual1);
let notEqual2 = 10 != 100;
console.log(notEqual2);
let notEqual3 = "ayam" != "t-rex";
console.log(notEqual3);
let notEqual4 = 5 != 2;
console.log(notEqual4);
let notEqual5 = true != false;
console.log(notEqual5);
let notEqual6 = null != 0;
console.log(notEqual6);
let notEqual7 = undefined != 0;
console.log(notEqual7);
let notEqual8 = NaN != 0;
console.log(notEqual8);
let notEqual9 = 100 != 100;
console.log(notEqual9); 
let notEqual10 = -1 != 0;
console.log(notEqual10);

// Perbandingan Tidak Sama Dengan termasuk Tipe Datanya
let notEqualTo1 = 5 !== 3;
console.log(notEqualTo1);
let notEqualTo2 = 10 !== 100;
console.log(notEqualTo2);
let notEqualTo3 = "ayam" !== "t-rex";
console.log(notEqualTo3);
let notEqualTo4 = 5 !== 2;
console.log(notEqualTo4);
let notEqualTo5 = true !== false;
console.log(notEqualTo5);
let notEqualTo6 = null !== 0;
console.log(notEqualTo6);
let notEqualTo7 = undefined !== 0;
console.log(notEqualTo7);
let notEqualTo8 = NaN !== 0;
console.log(notEqualTo8);
let notEqualTo9 = 100 !== 100;
console.log(notEqualTo9); 
let notEqualTo10 = -1 !== 0;
console.log(notEqualTo10);